version: '2.3'
services:
  train-fold:
    container_name: train_gpu${NVIDIA_VISIBLE_DEVICES}_${PROJECT_NAME}
    runtime: ${DOCKER_RUNTIME}
    build:
      context: ../../..
      dockerfile: docker/train/tensorflow-fold/Dockerfile.${DOCKERFILE_EXT}
      args:
        OWN_LOCATION: docker/train/tensorflow-fold
        PROJECT_ROOT: /root/recursive-embedding
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
    image: tensorflowfold:${DOCKERFILE_EXT}
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_TRAIN}:/root/train
      - ${HOST_CORPORA_OUT}:/root/corpora_out
#    ports:
#      - ${HOST_PORT_NOTEBOOK}:8888
    command: >
        --train_data_path=/root/corpora_out/${TRAIN_DATA}
        --logdir=/root/train/${TRAIN_LOGDIR}
        --logdir_pretrained=/root/train/${LOGDIR_PRETRAINED}
        --model_type=${MODEL_TYPE}
        --task=${TASK}
        --dev_file_indices=${DEV_FILE_INDICES}
        --batch_size=${BATCH_SIZE}
        --tree_embedder=${TREE_EMBEDDER}
        --use_tfidf=${USE_TFIDF}
        --learning_rate=${LEARNING_RATE}
        --optimizer=${OPTIMIZER}
        --early_stopping_window=${EARLY_STOPPING_WINDOW}
        --early_stopping_metric=${EARLY_STOPPING_METRIC}
        --root_fc_sizes=${ROOT_FC_SIZES}
        --leaf_fc_size=${LEAF_FC_SIZE}
        --fc_sizes=${FC_SIZES}
        --state_size=${STATE_SIZE}
        --keep_prob=${KEEP_PROB}
        --init_only=${INIT_ONLY}
        --concat_mode=${CONCAT_MODE}
        --max_depth=${MAX_DEPTH}
        --context=${CONTEXT}
        --link_cost_ref=${LINK_COST}
        --neg_samples=${NEG_SAMPLES}
        --train_files=${TRAIN_FILES}
        --test_files=${TEST_FILES}
        --no_fixed_vecs=${NO_FIXED_VECS}
        --all_vecs_fixed=${ALL_VECS_FIXED}
        --var_vecs_zero=${VAR_VECS_ZERO}
        --var_vecs_random=${VAR_VECS_RANDOM}
        --batch_iter=${BATCH_ITER}
        --batch_iter_test=${BATCH_ITER_TEST}
        --nbr_trees=${NBR_TREES}
        --nbr_trees_test=${NBR_TREES_TEST}
        --additional_vecs=${ADDITIONAL_VECS}
        --grid_config_file=${GRID_CONFIG_FILE}
        --run_count=${RUN_COUNT}
        --reuse_embeddings=${REUSE_EMBEDDINGS}
        --dump_trees=${DUMP_TREES}
        --sequence_length=${SEQUENCE_LENGTH}
        --precompile=${PRECOMPILE}
        --dont_test=${DONT_TEST}
        --debug=${DEBUG}
        --discard_tree_embeddings=${DISCARD_TREE_EMBEDDINGS}
        --discard_prepared_embeddings=${DISCARD_PREPARED_EMBEDDINGS}
        --use_circular_correlation=${USE_CIRCULAR_CORRELATION}
    cpuset: ${CPU_SET}
    mem_limit: ${MEM_LIMIT}

  tensorboard:
    image: tensorflow/tensorflow:1.4.1
    volumes:
      - ${HOST_TRAIN}:/root/train
      - ${HOST_CORPORA_OUT}:/root/corpora_out
#    ports:
#      - ${HOST_PORT_TENSORBOARD}:6006
    command: >
      tensorboard --logdir=/root/train/${TRAIN_LOGDIR}