version: '2.3'
services:
  train-fold:
    runtime: ${DOCKER_RUNTIME}
    build:
      context: ../../..
      dockerfile: docker/train/tensorflow-fold/Dockerfile.${DOCKERFILE_EXT}
      args:
        OWN_LOCATION: docker/train/tensorflow-fold
        PROJECT_ROOT: /root/recursive-embedding
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
    image: tensorflowfold:${DOCKERFILE_EXT}
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_TRAIN}:/root/train
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    ports:
      - ${HOST_PORT_NOTEBOOK}:8888
    command: >
        --train_data_path=/root/corpora_out/${TRAIN_DATA}
        --logdir=/root/train/${TRAIN_LOGDIR}
        --model_type=${MODEL_TYPE}
        --dev_file_index=${DEV_FILE_INDEX}
        --batch_size=${BATCH_SIZE}
        --tree_embedder=${TREE_EMBEDDER}
        --learning_rate=${LEARNING_RATE}
        --optimizer=${OPTIMIZER}
        --early_stop_queue=${EARLY_STOP_QUEUE}
        --root_fc_sizes=${ROOT_FC_SIZES}
        --leaf_fc_size=${LEAF_FC_SIZE}
        --fc_sizes=${FC_SIZES}
        --state_size=${STATE_SIZE}
        --keep_prob=${KEEP_PROB}
        --init_only=${INIT_ONLY}
        --concat_mode=${CONCAT_MODE}
        --max_depth=${MAX_DEPTH}
        --context=${CONTEXT}
        --neg_samples=${NEG_SAMPLES}
        --neg_samples_test=${NEG_SAMPLES_TEST}
        --train_files=${TRAIN_FILES}
        --no_fixed_vecs=${NO_FIXED_VECS}
        --batch_iter=${BATCH_ITER}
        --batch_iter_test=${BATCH_ITER_TEST}
    cpuset: ${CPU_SET}
    mem_limit: ${MEM_LIMIT}

  tensorboard:
    image: tensorflow/tensorflow:1.4.1
    volumes:
      - ${HOST_TRAIN}:/root/train
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    ports:
      - ${HOST_PORT_TENSORBOARD}:6006
    command: >
      tensorboard --logdir=/root/train/${TRAIN_LOGDIR}