version: '2.3'
services:
  train-fold-cpu:
    build:
      context: ../../..
      dockerfile: docker/train/tensorflow-fold/Dockerfile.tf1_3_cpu_mkl
      args:
        OWN_LOCATION: docker/train/tensorflow-fold
        PROJECT_ROOT: /root/recursive-embedding
    image: tensorflowfold:tf1_3_cpu_mkl
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_TRAIN}:/root/train
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    ports:
      - ${HOST_PORT_NOTEBOOK}:8888
    command: >
                                  --train_data_path=/root/corpora_out/${TRAIN_DATA}
                                  --logdir=/root/train/${TRAIN_LOGDIR}
                                  --model_type=tuple
                                  --dev_file_index=0
                                  --batch_size=10
                                  --tree_embedder=TreeEmbedding_HTU_reduceSUM_mapGRU
                                  --learning_rate=0.003
                                  --optimizer=AdamOptimizer
                                  --early_stop_queue=0
                                  --root_fc_size=0
                                  --leaf_fc_size=300
                                  --state_size=150
                                  --keep_prob=0.9
                                  --init_only=False
                                  --concat_mode=tree
                                  --max_depth=10
                                  --context=0
#    cpus: ${LIMIT_CPUS}
    cpuset: ${CPU_SET}


## ATTENTION: THIS IS DEPRECATED. Training via nvidia-docker can not be restricted to some GPUs, when called by
## docker-compose. Use train.sh instead (set the variable NV_GPU defined via .env file to enable training on GPU(s)).
  train-fold-gpu:
    runtime: nvidia
    build:
      context: ../../..
      dockerfile: docker/train/tensorflow-fold/Dockerfile.tf1_3_gpu
      args:
        OWN_LOCATION: docker/train/tensorflow-fold
        PROJECT_ROOT: /root/recursive-embedding
    image: tensorflowfold:tf1_3_gpu
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_TRAIN}:/root/train
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    ports:
      - ${HOST_PORT_NOTEBOOK}:8888
#    devices:
#      - "/dev/nvidiactl:/dev/nvidiactl"
#      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
#      - "/dev/nvidia6:/dev/nvidia7"
    command: >
      /root/recursive-embedding/set-user-with-folder.sh /root/train python train_fold.py
                                  --train_data_path=/root/corpora_out/${TRAIN_DATA}
                                  --logdir=/root/train/${TRAIN_LOGDIR}
                                  --model_type=tuple
                                  --dev_file_index=0
                                  --batch_size=10
                                  --tree_embedder=TreeEmbedding_HTU_reduceSUM_mapGRU
                                  --learning_rate=0.003
                                  --optimizer=AdamOptimizer
                                  --early_stop_queue=0
                                  --root_fc_size=0
                                  --leaf_fc_size=300
                                  --state_size=150
                                  --keep_prob=0.9
                                  --init_only=False
                                  --concat_mode=tree
                                  --max_depth=10
                                  --context=0
#    cpus: ${LIMIT_CPUS}
    cpuset: ${CPU_SET}

  tensorboard:
    image: tensorflow/tensorflow:1.4.1
    volumes:
      - ${HOST_TRAIN}:/root/train
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    ports:
      - ${HOST_PORT_TENSORBOARD}:6006
    command: >
      tensorboard --logdir=/root/train/${TRAIN_LOGDIR}