version: '2.3'
services:
  visualize:
    runtime: ${DOCKER_RUNTIME}
    build:
      context: ../../..
      dockerfile: docker/tools/visualize/${DOCKERFILE}
      args:
          OWN_LOCATION: docker/tools/visualize
          PROJECT_ROOT: /root/recursive-embedding
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
    ports:
      - ${HOST_PORT}:5000
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
      - ${HOST_TRAIN}:/root/train
    command: >
      /root/set-user-with-folder.sh /root/recursive-embedding python embedding_api.py
    cpuset: ${CPU_SET}
    mem_limit: ${MEM_LIMIT}
