version: '2.3'
services:
  visualize:
    runtime: ${DOCKER_RUNTIME}
    build:
      context: ../../..
      dockerfile: docker/tools/visualize/Dockerfile
    ports:
      - ${HOST_PORT}:5000
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/corpora_out python embedding_api.py
