version: '2.3'
services:
  corpus-dbpedia-nif-prepare:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/bioasq/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_IN}:/root/corpora_in
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/corpora_out python corpus_bioasq.py PARSE_BATCHES
                                  --in-path /root/corpora_in/${BIOASQ_SUBDIR}
                                  --out-path /root/corpora_out/BIOASQ
                                  --num-threads-parse ${NUM_THREADS_PARSE}
                                  --batch-size-parse ${BATCH_SIZE_PARSE}
    cpuset: ${CPU_SET}
    mem_limit: ${MEM_LIMIT}

  corpus-dbpedia-nif-merge:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/bioasq/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/corpora_out python corpus_dbpedianif.py MERGE_BATCHES
                                  --out-path /root/corpora_out/BIOASQ
                                  --min-count ${MIN_COUNT}
    cpuset: ${CPU_SET}
    mem_limit: ${MEM_LIMIT}