version: '2.3'
services:
  corpus-bioasq-prepare:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/bioasq/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_IN}:/root/corpora_in
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/corpora_out python corpus_bioasq.py PREPARE_BATCHES
                                  --in-path /root/corpora_in/${BIOASQ_SUBDIR}
                                  --mapping-file /root/recursive-embedding/Structured-Abstracts-Labels.txt
                                  --n-threads ${NUM_THREADS_PREPARE}
    cpuset: ${CPU_SET}
    mem_limit: ${MEM_LIMIT}

  corpus-bioasq-parse:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/bioasq/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_IN}:/root/corpora_in
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/corpora_out python corpus_bioasq.py PARSE_BATCHES
                                  --in-path /root/corpora_in/${BIOASQ_SUBDIR}
                                  --out-path /root/corpora_out/BIOASQ
                                  --n-threads ${NUM_THREADS_PARSE}
                                  --parser-batch-size ${BATCH_SIZE_PARSE}
    cpuset: ${CPU_SET}
    mem_limit: ${MEM_LIMIT}

  corpus-bioasq-merge:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/bioasq/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/corpora_out python corpus_dbpedianif.py MERGE_BATCHES
                                  --out-path /root/corpora_out/BIOASQ
                                  --min-count ${MIN_COUNT}
    cpuset: ${CPU_SET}
    mem_limit: ${MEM_LIMIT}