version: '2.3'
services:
  corpus-parse:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/imdb/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_IN}:/root/corpora_in
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/recursive-embedding/src python corpus_imdb.py PARSE
                                  --in-path /root/corpora_in
                                  --out-path /root/corpora_out/IMDB
                                  --n-threads ${NUM_THREADS_PARSE}
                                  --parser-batch-size ${BATCH_SIZE_PARSE}
                                  --sentence-processor ${SENTENCE_PROCESSOR}
    cpuset: ${CPU_SET}
    mem_limit: ${MEM_LIMIT}

  corpus-merge:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/imdb/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/recursive-embedding/src python corpus_imdb.py MERGE
                                  --out-path /root/corpora_out/IMDB
                                  --min-count ${MIN_COUNT}
                                  --coverage ${COVERAGE}
    cpuset: ${CPU_SET}
    mem_limit: ${MEM_LIMIT}

  corpus-indices:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/imdb/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/recursive-embedding/src python corpus_imdb.py CREATE_INDICES
                                  --merged-forest-path /root/corpora_out/IMDB/merged/forest
                                  --split-count ${SPLIT_COUNT}
                                  --start-root ${START_ROOT}
                                  --end-root ${END_ROOT}

  corpus-indices-test:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/imdb/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/recursive-embedding/src python corpus_imdb.py CREATE_INDICES
                                  --merged-forest-path /root/corpora_out/IMDB/merged/forest
                                  --split-count ${SPLIT_COUNT}
                                  --start-root 0
                                  --end-root 25000
                                  --suffix test
  corpus-indices-train:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/imdb/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/recursive-embedding/src python corpus_imdb.py CREATE_INDICES
                                  --merged-forest-path /root/corpora_out/IMDB/merged/forest
                                  --split-count ${SPLIT_COUNT}
                                  --start-root 25000
                                  --end-root -1
                                  --suffix train
