version: '2.3'
services:
  virt-dbpedia-nif:
    image: "joernhees/virtuoso:latest"
    ports:
      - "8890:8890"
      - "1111:1111"
    volumes:
      - ${HOST_VIRTUOSO_DATA}:/var/lib/virtuoso-opensource-7
    environment:
      - NumberOfBuffers=${DB_NUMBER_OF_BUFFERS}
  corpus-dbpedia-nif-prepare:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/dbpedia-nif/Dockerfile
    depends_on:
      - virt-dbpedia-nif
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/corpora_out python corpus_dbpedianif.py PREPARE_BATCHES
                                  --out-path /root/corpora_out/DBPEDIANIF
                                  --batch-size ${BATCH_SIZE}
                                  --start-offset ${START}
                                  --batch-count=${BATCH_COUNT}
    cpus: ${LIMIT_CPUS}
    cpuset: ${CPU_SET}

  corpus-dbpedia-nif-batches:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/dbpedia-nif/Dockerfile
    depends_on:
      - virt-dbpedia-nif
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/corpora_out python corpus_dbpedianif.py CREATE_BATCHES
                                  --out-path /root/corpora_out/DBPEDIANIF
                                  --batch-size ${BATCH_SIZE}
                                  --batch-size-parse ${BATCH_SIZE_PARSE}
                                  --num-threads-query ${NUM_THREADS_QUERY}
                                  --num-threads-parse ${NUM_THREADS_PARSE}
                                  --num-threads-parse-pipe ${NUM_THREADS_PARSE_PIPE}
    cpus: ${LIMIT_CPUS}
    cpuset: ${CPU_SET}
  corpus-dbpedia-nif-merge:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/dbpedia-nif/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/corpora_out python corpus_dbpedianif.py MERGE_BATCHES
                                  --out-path /root/corpora_out/DBPEDIANIF/${BATCH_SIZE}
                                  --min-count ${MIN_COUNT}
                                  --min-count-root-id ${MIN_COUNT_ROOT_ID}
    cpus: ${LIMIT_CPUS}
    cpuset: ${CPU_SET}

  corpus-dbpedia-nif-indices:
    build:
      context: ../../..
      dockerfile: docker/create-corpus/dbpedia-nif/Dockerfile
    volumes:
      - ../../../src:/root/recursive-embedding/src
      - ${HOST_CORPORA_OUT}:/root/corpora_out
    command: >
      /root/set-user-with-folder.sh /root/corpora_out python corpus_dbpedianif.py CREATE_INDICES
                                  --merged-forest-path /root/corpora_out/DBPEDIANIF/${BATCH_SIZE}/merged/forest
                                  --seealso-min ${SEEALSO_MIN_COUNT}
                                  --seealso-max ${SEEALSO_MAX_COUNT}
                                  --split-count ${SPLIT_COUNT}
    cpus: ${LIMIT_CPUS}
    cpuset: ${CPU_SET}